package com.seatreservation.logging;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.seatreservation.dto.CreateShowRequest;
import com.seatreservation.dto.ReserveSeatRequest;
import com.seatreservation.security.JwtService;
import io.zonky.test.db.AutoConfigureEmbeddedDatabase;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.http.MediaType;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.test.web.servlet.MockMvc;

import java.util.List;

import static org.hamcrest.Matchers.equalTo;
import static org.hamcrest.Matchers.notNullValue;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.post;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.header;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

@SpringBootTest
@AutoConfigureMockMvc
@AutoConfigureEmbeddedDatabase(type = AutoConfigureEmbeddedDatabase.DatabaseType.POSTGRES)
@ActiveProfiles("test")
class LoggingIntegrationTest {

    @Autowired
    private MockMvc mockMvc;

    @Autowired
    private ObjectMapper objectMapper;

    @Autowired
    private JwtService jwtService;

    @Test
    @DisplayName("Request ID: Should propagate client-provided X-Request-ID in response header and MDC logs")
    void testCustomRequestIdPropagation() throws Exception {
        String clientRequestId = "custom-client-req-999";

        mockMvc.perform(get("/health/live")
                .header("X-Request-ID", clientRequestId))
            .andExpect(status().isOk())
            .andExpect(header().string("X-Request-ID", equalTo(clientRequestId)));
    }

    @Test
    @DisplayName("Request ID: Should generate UUID when X-Request-ID is not provided")
    void testAutoGeneratedRequestId() throws Exception {
        mockMvc.perform(get("/health/live"))
            .andExpect(status().isOk())
            .andExpect(header().string("X-Request-ID", notNullValue()));
    }

    @Test
    @DisplayName("Structured Logs: Reservation success and decline write correlation ID and domain event")
    void testReservationLogEvents() throws Exception {
        String adminToken = "Bearer " + jwtService.generateToken("admin", "ADMIN");
        String userToken = "Bearer " + jwtService.generateToken("log-user", "USER");

        // 1. Create show
        CreateShowRequest showRequest = new CreateShowRequest("log-show", List.of("L1"), 25000L, 4);
        String createRes = mockMvc.perform(post("/shows")
                .header("Authorization", adminToken)
                .header("X-Request-ID", "req-create-show-log")
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(showRequest)))
            .andExpect(status().isCreated())
            .andExpect(header().string("X-Request-ID", "req-create-show-log"))
            .andReturn()
            .getResponse()
            .getContentAsString();

        String showId = objectMapper.readTree(createRes).get("id").asText();

        // 2. Reserve seat L1 (RESERVATION_CONFIRMED)
        mockMvc.perform(post("/shows/" + showId + "/reserve")
                .header("Authorization", userToken)
                .header("X-Request-ID", "req-reserve-log-1")
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(new ReserveSeatRequest(List.of("L1")))))
            .andExpect(status().isCreated())
            .andExpect(header().string("X-Request-ID", "req-reserve-log-1"));

        // 3. Attempt duplicate reserve (RESERVATION_DECLINED)
        mockMvc.perform(post("/shows/" + showId + "/reserve")
                .header("Authorization", userToken)
                .header("X-Request-ID", "req-reserve-log-2")
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(new ReserveSeatRequest(List.of("L1")))))
            .andExpect(status().isConflict())
            .andExpect(header().string("X-Request-ID", "req-reserve-log-2"));
    }
}
